---
openapi: 3.0.0
info:
  title: API сервиса доставки отправлений
  description: ""
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/ZINASHEMBULATOVA/deliveryAPI-test/1.0.0
  description: тест
- url: https://virtserver.swaggerhub.com/ZINASHEMBULATOVA/deliveryAPI/1.0.0
  description: прод
paths:
  /order:
    post:
      summary: Создать заказ доставки
      description: Метод позволяет создать заказ доставки отправления
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestCreateOrder'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseCreateOrder'
        "400":
          description: Bad Request
  /order/{number}:
    get:
      summary: Получить информацию о заказе доставки
      description: Метод позволяет получить информацию о заказе доставки отправления
      parameters:
      - name: number
        in: path
        description: Номер заказа
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetInfoOrder'
        "404":
          description: Not found. Заказ не найден
    patch:
      summary: Обновить статус заказа
      description: Метод позволяет частично обновить информацию о заказе доставки отправления, а именно статус заказа
      parameters:
      - name: number
        in: path
        description: Номер заказа
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestUpdateStatus'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetInfoOrder'
        "404":
          description: Not found. Заказ не найден
  /order/findByStatus:
    get:
      summary: Получить список заказов с фильтрацией по статусу заказа
      description: Метод позволяет получить список заказов доставки отправления с фильтрацией по статусу заказа
      parameters:
      - name: status
        in: query
        description: Статус заказа
        required: true
        schema:
          type: string
          enum:
            - CREATED
            - CANCELLED
            - IN_PROGRESS
            - COMPLETED
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetListOrder'
        "400":
          description: Bad request
components:
  schemas:
    ResponseGetInfoOrder:
      type: object
      properties:
        number:
          type: integer
          description: Номер заказа
          format: int64
          example: 1034567
        barcode:
          type: string
          description: Номер отправления
          example: 80080184811117
        status:
          type: string
          description: Статус заказа
          example: CREATED
          enum:
            - CREATED
            - CANCELLED
            - IN_PROGRESS
            - COMPLETED
        recipient:
          type: object
          properties:
           name:
            type: string
            description: Имя получателя
            example: Иванов Иван
           address:
            type: string
            description: Адрес получателя  
            example: Санкт-Петербург, Невский проспект, 1
           phone:
            type: string
            description: Телефон
            example: 8-911-933-8902
    RequestCreateOrder:
      type: object
      properties:
        barcode:
          type: string
          description: Номер отправления
          example: 80080184811117
        recipient:
          type: object
          properties:
           name:
            type: string
            description: Имя получателя
            example: Иванов Иван
           address:
            type: string
            description: Адрес получателя  
            example: Санкт-Петербург, Невский проспект, 1
           phone:
            type: string
            description: Телефон
            example: 8-911-933-8902
    ResponseCreateOrder:
      type: object
      properties:
        number:
          type: integer
          description: Номер заказа
          format: int64
          example: 78900006
        status:
          type: string
          description: Статус заказа
          example: CREATED
          enum:
          - CREATED
    RequestUpdateStatus:
      type: object
      properties:
        status:
          type: string
          description: Статус заказа
          example: CREATED
          enum:
            - CANCELLED
            - IN_PROGRESS
            - COMPLETE
    ResponseGetListOrder:
      type: array
      items:
        $ref: '#/components/schemas/ResponseGetInfoOrder'